
import { AntdRegistry } from '@ant-design/nextjs-registry';
import '@/app/globals.css'
import ConditionalLayout from '@/components/ConditionalLayout';
import { AuthProvider } from '@/contexts/AuthContext';



export const metadata = {
  title: 'Admin',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

        <AuthProvider>
          <AntdRegistry>
            <ConditionalLayout>


              {children}
            </ConditionalLayout>
          </AntdRegistry>
        </AuthProvider>
      </body>
    </html>
  )
}
