import { AntdRegistry } from '@ant-design/nextjs-registry';
import '@/app/globals.css'
import MenuComponent from '@/components/MenuComponent';

export const metadata = {
  title: 'Admin',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <div className="layout-container">
            <aside className="sidebar">
              <MenuComponent />
            </aside>
            <main className="content">
              {children}
            </main>
          </div>
        </AntdRegistry>
      </body>
    </html>
  )
}
